train:
  _target_: methods.robust.data.adapter.RobustDatasetAdapter
  dataset:
    _target_: methods.common.datasets.tsworldcup.TsWorldCupDataset
    subset_filepath: .scratch/dataset/tsworldcup/train.txt
  noise_translate: ${common.noise_translate}
  noise_rotate: ${common.noise_rotate}
  random_flip: True

val:
  _target_: methods.robust.data.adapter.RobustDatasetAdapter
  dataset:
    _target_: methods.common.datasets.tsworldcup.TsWorldCupDataset
    subset_filepath: .scratch/dataset/tsworldcup/test.txt
  noise_translate: 0.0
  noise_rotate: 0.0
  random_flip: False
